### ISSUE TITLE
Re-organize all.sh to make it PSA-Crypto friendly

### ISSUE THREAD

**Issue by ronald-cron-arm** [Mbed-TLS/TF-PSA-Crypto#31]
Split all.sh into two files: everything but the components (all.sh framework) and the test components. Mbed-TLS and PSA-Crypto share the all.sh framework and both have their own test components file.
With this we should be able to get rid of `replace_all_sh_components` in `scripts/psa_crypto.py`.

**Comment by mpg** [comment]
Re-opening as #8226:
- needs to have its backport merged -> #9444
- was only the beginning: now we want tf-psa-crypto to be able to have its own components file (that might have to wait until it has its own build system though)

**Comment by ronald-cron-arm** [comment]
Closing as the split of the components out of all.sh has been been (https://github.com/Mbed-TLS/mbedtls/pull/9444). The TF-PSA-Crypto all.sh components will be covered by an EPIC.
