### ISSUE TITLE
Use `lcov.sh` in PSA Crypto repo

### ISSUE THREAD

**Issue by davidhorstmann-arm** [Mbed-TLS/TF-PSA-Crypto#41]
Generating coverage data in the Mbed TLS repo is done by the script `lcov.sh`. In the PSA Crypto repo it is currently done inline in the `lcov` target in CMake.

It would be best to unify these two approaches by using the `lcov.sh` script in PSA Crypto. However, this script cannot be used directly in PSA Crypto as it refers to the `library` directory, which is unique to Mbed TLS.

This task consists of 2 parts:
1. Modify `lcov.sh` so that it works in either the Mbed TLS or PSA Crypto repo.
2. Add `lcov.sh` to the PSA Crypto repo and use it in the CMake `lcov` target.

**Comment by ronald-cron-arm** [comment]
Done in #87
