### ISSUE TITLE
Add change log support

### ISSUE THREAD

**Issue by ronald-cron-arm** [Mbed-TLS/TF-PSA-Crypto#47]
Add change log support

- [ ] Add an initial empty ChangeLog or almost empty file
- [ ] Create the ChangeLog.d with its 00README.md
- [ ] Adapt assemble_changelog.py to work for both mbedtls and psa-cryto repo
- [ ] Add check_changelog all.sh component

DOD: Same support for change logs in psa-crypto as in mbedtls

**Comment by ronald-cron-arm** [comment]
#90 still to review and merge

**Comment by gabor-mezei-arm** [comment]
All related PRs merged
