### ISSUE TITLE
Add support for psa-crypto in config.py

### ISSUE THREAD

**Issue by ronald-cron-arm** [Mbed-TLS/TF-PSA-Crypto#58]
Add support for psa-crypto repo in config.py regarding the options `baremetal`,`baremetal_size`,`full`,`full_no_deprecated`,`realfull`,`crypto`,`crypto_baremetal`,`crypto_full`.

The configuration file in psa-crypto is include/psa/crypto_config.h. It contains PSA_CRYPTO_ and PSA_WANT_ configuration options and thus config.py should be able to handle those configuration options.

We have in build_tree.py looks_like_psa_crypto_root() to detect if we are in the mbedtls or psa-crypto repo.

In psa-crypto, `baremetal` and `crypto_baremetal` are equivalent, as well as `full` and `crypto_full`. crypto does not do anything, just the default psa-crypto configuration.

**Comment by ronald-cron-arm** [comment]
Superseded by https://github.com/Mbed-TLS/mbedtls/issues/9157 and https://github.com/Mbed-TLS/mbedtls/issues/9158.

**Comment by ronald-cron-arm** [comment]
Superseded by https://github.com/Mbed-TLS/mbedtls/issues/9157 and https://github.com/Mbed-TLS/mbedtls/issues/9158.

**Comment by ronald-cron-arm** [comment]
Superseded by https://github.com/Mbed-TLS/mbedtls/issues/9157 and https://github.com/Mbed-TLS/mbedtls/issues/9158.

**Comment by gilles-peskine-arm** [comment]
`baremetal` and `baremetal_size` still doesn't exist in TF-PSA-Crypto 1.0. This is covered by https://github.com/Mbed-TLS/TF-PSA-Crypto/issues/526.
